import Head from 'next/head';
import useSWR from 'swr';
import { CircularProgress } from '@mui/material';

export default function Home() {
  const { data } = useSWR('/api/tweets');

  if (!data) return <CircularProgress />;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <p>Hello!</p>
    </>
  );
}
